title = "LinkTracker"
gitRepoUrl = "https://github.com/re-sync-dev/LinkTracker" # From Git
gitSourceBranch = "main"
changelog = true

[docusaurus]
favicon = "/icon.png"
onBrokenLinks = "ignore"
onBrokenMarkdownLinks = "warn"

# From git:
url = "https://re-sync-dev.github.io"
baseUrl = "/LinkTracker"
tagline = "Allowing developers to do more with their promotional content/material."

[navbar]
title = ""

[navbar.logo]
src = "/icon.png"
alt = "LinkTracker"

[home]
enabled = true
includeReadme = false

[footer]
style = "dark"
copyright = "Copyright © 2024 Re-Sync. Built with Moonwave and Docusaurus"
