[package]
name = "vyon/linktracker"
description = "LinkTracker is a package that allows developers to do more with promotional content/material."
version = "1.2.1"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT"
realm = "shared"
authors = ["Vyon (https://github.com/Vyon)"]

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.toml"]

[dependencies]
# Utility
T = "osyrisrblx/t@3.0.0"
HashLib = "boatbomber/hashlib@1.0.0"
